/*
 * sample-data.js — 内置示例（内容与 samples/lines.yml、samples/stops.yml 一致），
 * 便于离线一键体验（浏览器直接打开 index.html 时无法 fetch 本地文件）。
 */
(function (root) {
    'use strict';
    var MMS = (root.MMS = root.MMS || {});

    var SAMPLE_LINES = [
        '# 示例：云屿市轨道交通 lines.yml',
        'line1:',
        '  name: 1号线',
        "  color: '&#E4353B'",
        '  ordered_stop_ids:',
        '    - l1_redcliff',
        '    - l1_orchard',
        '    - l1_westgate',
        '    - l1_oldtown',
        '    - l1_library',
        '    - l1_centralpark',
        '    - l1_civic',
        '    - l1_museum',
        '    - l1_university',
        '    - l1_stadium',
        '    - l1_eastlake',
        '    - l1_airport',
        '  route_points:',
        '    - world,-640,64,-80',
        '    - world,-600,64,-74',
        '    - world,-560,64,-63',
        '    - world,-500,64,-56',
        '    - world,-460,64,-44',
        '    - world,-420,64,-40',
        '    - world,-380,64,-29',
        '    - world,-340,64,-20',
        '    - world,-300,64,-12',
        '    - world,-260,64,-3',
        '    - world,-220,64,1',
        '    - world,-180,64,9',
        '    - world,-140,64,15',
        '    - world,-100,64,20',
        '    - world,-60,64,24',
        '    - world,-20,64,27',
        '    - world,20,64,30',
        '    - world,60,64,30',
        '    - world,100,64,30',
        '    - world,140,64,29',
        '    - world,180,64,26',
        '    - world,220,64,20',
        '    - world,260,64,14',
        '    - world,300,64,6',
        '    - world,340,64,0',
        '    - world,380,64,-8',
        '    - world,420,64,-14',
        '    - world,460,64,-19',
        '    - world,500,64,-30',
        '    - world,540,64,-42',
        '    - world,560,64,-50',
        '',
        'line2:',
        '  name: 2号线',
        "  color: '&#2E6FD9'",
        '  ordered_stop_ids:',
        '    - l2_northyard',
        '    - l2_waterworks',
        '    - l2_stadiumnorth',
        '    - l2_centralpark',
        '    - l2_civic',
        '    - l2_southgate',
        '    - l2_railway',
        '    - l2_southyard',
        '',
        'line3:',
        '  name: 3号线',
        "  color: '&#22A06B'",
        '  ordered_stop_ids:',
        '    - l3_westport',
        '    - l3_market',
        '    - l3_university',
        '    - l3_eastpark',
        '    - l3_railway',
        ''
    ].join('\n');

    var SAMPLE_STOPS = [
        '# 示例：云屿市轨道交通 stops.yml',
        'l1_redcliff:',
        '  display_name: 红崖',
        '  corner1_location: world,-646,64,-86',
        '  corner2_location: world,-634,70,-74',
        '  stoppoint_location: world,-640,64,-80',
        '  launch_yaw: 90.0',
        '',
        'l1_orchard:',
        '  display_name: 果园',
        '  stoppoint_location: world,-540,64,-60',
        '',
        'l1_westgate:',
        '  display_name: 西门',
        '  stoppoint_location: world,-440,64,-40',
        '',
        'l1_oldtown:',
        '  display_name: 老城',
        '  stoppoint_location: world,-330,64,-20',
        '',
        'l1_library:',
        '  display_name: 图书馆',
        '  stoppoint_location: world,-215,64,0',
        '',
        'l1_centralpark:',
        '  display_name: 中央公园',
        '  stoppoint_location: world,-100,64,20',
        '  transferable_lines:',
        '    - line2',
        '',
        'l1_civic:',
        '  display_name: 市民广场',
        '  stoppoint_location: world,10,64,30',
        '  transferable_lines:',
        '    - line2',
        '',
        'l1_museum:',
        '  display_name: 博物馆',
        '  stoppoint_location: world,120,64,30',
        '',
        'l1_university:',
        '  display_name: 大学城',
        '  stoppoint_location: world,230,64,20',
        '  transferable_lines:',
        '    - line3',
        '',
        'l1_stadium:',
        '  display_name: 体育馆',
        '  stoppoint_location: world,340,64,0',
        '',
        'l1_eastlake:',
        '  display_name: 东湖',
        '  stoppoint_location: world,450,64,-20',
        '',
        'l1_airport:',
        '  display_name: 机场',
        '  stoppoint_location: world,560,64,-50',
        '',
        '# 旧版键名示例（1.1.x 格式）',
        'l2_northyard:',
        '  name: 北苑',
        '  corner1: world,-96,64,-306',
        '  corner2: world,-84,70,-294',
        '  stopPoint: world,-90,64,-300',
        '  launchYaw: 0.0',
        '',
        'l2_waterworks:',
        '  display_name: 水厂',
        '  stoppoint_location: world,-95,64,-210',
        '',
        'l2_stadiumnorth:',
        '  display_name: 体育馆北',
        '  stoppoint_location: world,-98,64,-120',
        '',
        'l2_centralpark:',
        '  display_name: 中央公园',
        '  stoppoint_location: world,-100,64,20',
        '  transferable_lines:',
        '    - line1',
        '',
        'l2_civic:',
        '  display_name: 市民广场',
        '  stoppoint_location: world,10,64,30',
        '  transferable_lines:',
        '    - line1',
        '',
        'l2_southgate:',
        '  display_name: 南门',
        '  stoppoint_location: world,60,64,120',
        '',
        'l2_railway:',
        '  display_name: 火车站',
        '  stoppoint_location: world,90,64,220',
        '  transferable_lines:',
        '    - line3',
        '',
        'l2_southyard:',
        '  display_name: 南苑',
        '  stoppoint_location: world,110,64,320',
        '',
        '# 未设置停靠点的示例（按区域中心估算）',
        'l3_westport:',
        '  display_name: 西港',
        '  corner1_location: world,-386,64,154',
        '  corner2_location: world,-374,70,166',
        '  launch_yaw: 45.0',
        '',
        'l3_market:',
        '  display_name: 集贸市场',
        '  stoppoint_location: world,-260,64,150',
        '',
        'l3_university:',
        '  display_name: 大学城',
        '  stoppoint_location: world,230,64,20',
        '  transferable_lines:',
        '    - line1',
        '',
        'l3_eastpark:',
        '  display_name: 东园',
        '  stoppoint_location: world,240,64,110',
        '',
        'l3_railway:',
        '  display_name: 火车站',
        '  stoppoint_location: world,90,64,220',
        '  transferable_lines:',
        '    - line2',
        ''
    ].join('\n');

    MMS.SAMPLE = {
        lines: SAMPLE_LINES,
        stops: SAMPLE_STOPS
    };
})(typeof window !== 'undefined' ? window : globalThis);
